/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 world.gltf 
Author: patrix (https://sketchfab.com/patrix)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/cathedral-faed84a829114e378be255414a7826ca
Title: Cathedral
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function World(props) {
  const { nodes, materials } = useGLTF('/world/world.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.03}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.base} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.base} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.base} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.base} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.base} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.base} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.base} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.base} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.base} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.base} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.base} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.base} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.base} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.base} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.base} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.base} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.base} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.base} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.base} />
        <mesh geometry={nodes.Object_21.geometry} material={materials.base} />
        <mesh geometry={nodes.Object_22.geometry} material={materials.base} />
        <mesh geometry={nodes.Object_23.geometry} material={materials.base} />
        <mesh geometry={nodes.Object_24.geometry} material={materials.base} />
        <mesh geometry={nodes.Object_25.geometry} material={materials.base} />
        <mesh geometry={nodes.Object_26.geometry} material={materials.base} />
        <mesh geometry={nodes.Object_27.geometry} material={materials.base} />
        <mesh geometry={nodes.Object_28.geometry} material={materials.base} />
        <mesh geometry={nodes.Object_29.geometry} material={materials.base} />
        <mesh geometry={nodes.Object_30.geometry} material={materials.transparent} />
        <mesh geometry={nodes.Object_31.geometry} material={materials.transparent} />
        <mesh geometry={nodes.Object_32.geometry} material={materials.transparent} />
        <mesh geometry={nodes.Object_33.geometry} material={materials.transparent} />
        <mesh geometry={nodes.Object_34.geometry} material={materials.transparent} />
      </group>
    </group>
  )
}

useGLTF.preload('/world/world.gltf')
